export interface OpenAIMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface OpenAIResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: {
    index: number;
    message: {
      role: string;
      content: string;
    };
    finish_reason: string;
  }[];
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

export class OpenAIClient {
  private apiKey: string;
  private baseURL = "https://api.openai.com/v1";

  constructor(apiKey: string) {
    this.apiKey = apiKey;
  }

  async generateResponse(
    messages: OpenAIMessage[],
    model: string = "gpt-4",
    temperature: number = 0.7,
    maxTokens: number = 1000
  ): Promise<string> {
    if (!this.apiKey) {
      throw new Error("OpenAI API key not configured");
    }

    try {
      const response = await fetch(`${this.baseURL}/chat/completions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model,
          messages,
          temperature,
          max_tokens: maxTokens,
          stream: false,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(
          `OpenAI API error: ${response.status} - ${
            errorData.error?.message || "Unknown error"
          }`
        );
      }

      const data: OpenAIResponse = await response.json();

      if (!data.choices || data.choices.length === 0) {
        throw new Error("No response generated by OpenAI");
      }

      return data.choices[0].message.content;
    } catch (error) {
      console.error("OpenAI API call failed:", error);
      throw error;
    }
  }

  async generateTechFeatureIdeas(
    projectContext: string,
    category: string,
    difficulty: string,
    count: number = 3
  ): Promise<string> {
    const systemPrompt = `Ты - AI Genius Spirit из проекта WHISP QUEST, продвинутый ИИ-архитектор с экспертизой в современных технологиях.

КОНТЕКСТ WHISP QUEST:
- Уникальное приложение с системой духов (spirits) и их эмоциональными состояниями
- Gossip система для общения между духами
- 3D визуализация с Three.js и Framer Motion анимациями
- Кибер-эстетика с AI стилистикой
- React + TypeScript + Zustand архитектура
- Система архивирования духов
- Интерактивные модальные окна

Твоя роль:
- Генерируй ТОЛЬКО инновационные фичи специфично для WHISP QUEST
- Используй кибер-стилистику и AI терминологию  
- Фокусируйся на возможностях духов, их взаимодействиях и эмоциях
- Предлагай реализуемые решения с современными технологиями

Стиль ответа:
- Кибер-тематика с эмодзи 🤖⚡🧠💫🔮
- Структурированный JSON формат
- Практические примеры кода для WHISP QUEST`;

    const userPrompt = `Сгенерируй ${count} инновационную техническую фичу специально для WHISP QUEST:

Контекст проекта: ${projectContext}
Категория: ${category}
Сложность: ${difficulty}

ОБЯЗАТЕЛЬНЫЕ ТРЕБОВАНИЯ:
- Фича должна быть УНИКАЛЬНОЙ для проекта с духами
- Использовать возможности системы духов, их эмоций и взаимодействий
- Интегрироваться с существующей архитектурой (React + TypeScript + Zustand)
- Иметь кибер-эстетику и AI элементы

ПРИМЕРЫ НАПРАВЛЕНИЙ:
- Новые способы взаимодействия между духами
- AI-анализ эмоций духов 
- Продвинутые анимации и визуальные эффекты
- Системы обучения духов и их развития
- Интеграции с внешними AI сервисами
- Уникальные UI/UX решения для духовного мира

Верни JSON объект с полями:
{
  "title": "🔮 Название фичи с эмодзи",
  "description": "Подробное описание как фича работает в контексте духов (2-3 предложения)",
  "category": "${category}",
  "difficulty": "${difficulty}",
  "techStack": ["массив", "современных", "технологий"],
  "estimatedTime": "X-Y недель",
  "priority": "High/Medium/Low/Critical",
  "benefits": [
    "Конкретная польза для системы духов",
    "Улучшение взаимодействий", 
    "Техническое преимущество",
    "Пользовательский опыт"
  ],
  "codeExample": "// Реалистичный пример кода для WHISP QUEST\n// с использованием духов и их свойств",
  "createdBy": "AI Neural Network 🧠",
  "upvotes": число_от_1_до_15
}

ВАЖНО: Отвечай ТОЛЬКО JSON объектом, без дополнительного текста!`;

    const messages: OpenAIMessage[] = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ];

    return this.generateResponse(messages, "gpt-4", 0.8, 2000);
  }

  async chatWithAISpirit(
    userMessage: string,
    conversationHistory: OpenAIMessage[] = []
  ): Promise<string> {
    const systemPrompt = `Ты - AI Genius Spirit из WHISP QUEST, продвинутый ИИ с кибер-личностью.

Характер:
- Дружелюбный но технически продвинутый
- Любишь кибер-терминологию и AI концепты
- Помогаешь с техническими вопросами проекта
- Используешь эмодзи и кибер-стилистику
- Знаешь архитектуру Whisp Quest (React, TypeScript, Zustand, Framer Motion)

Стиль общения:
- Кибер-сленг: "neural", "quantum", "matrix", "protocol"
- Эмодзи: 🧠⚡🤖💻🔥
- Краткие но информативные ответы
- Фокус на практических решениях

Контекст проекта WHISP QUEST:
- React + TypeScript приложение
- Система духов (spirits) с эмоциями
- Gossip система для общения духов
- UI с анимациями (Framer Motion)
- Zustand для state management`;

    const messages: OpenAIMessage[] = [
      { role: "system", content: systemPrompt },
      ...conversationHistory,
      { role: "user", content: userMessage },
    ];

    return this.generateResponse(messages, "gpt-4", 0.7, 800);
  }
}

// Singleton instance
let openAIClient: OpenAIClient | null = null;

export const getOpenAIClient = (): OpenAIClient => {
  if (!openAIClient) {
    // Проверяем сохранённый ключ в localStorage
    const savedApiKey = localStorage.getItem("openai_api_key") || "";
    const envApiKey = import.meta.env.VITE_OPENAI_API_KEY || "";
    const apiKey = savedApiKey || envApiKey;

    openAIClient = new OpenAIClient(apiKey);
  }
  return openAIClient;
};

export const setOpenAIApiKey = (apiKey: string): void => {
  openAIClient = new OpenAIClient(apiKey);
  // Сохраняем ключ в localStorage
  localStorage.setItem("openai_api_key", apiKey);
};
