version: "3.8"

services:
  # Frontend (React + Vite + Nginx)
  whisp-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisp-frontend
    ports:
      - "80:80"
    depends_on:
      - whisp-server
    environment:
      - NODE_ENV=production
    networks:
      - whisp-network
    restart: unless-stopped
    labels:
      - "com.docker.compose.service=frontend"

  # Backend (Express + OpenAI)
  whisp-server:
    build:
      context: ./whisp-server
      dockerfile: Dockerfile
    container_name: whisp-server
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
    env_file:
      - .env
    networks:
      - whisp-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3002/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.service=backend"

networks:
  whisp-network:
    driver: bridge
    labels:
      - "com.docker.compose.network=whisp-network"

volumes:
  # Том для логов nginx (опционально)
  nginx_logs:
    driver: local
